[[constraint]]
  name = "github.com/albenik/goerrors"
  version = "0.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
